export const GET_POSTS_ARR = "GET_POSTS_ARR";
export const ADD_NEW_POST = "ADD_NEW_POST";
export const CHANGE_LIKES_COUNTER = "CHANGE_LIKES_COUNTER";
export const CHANGE_SAVES_COUNTER = "CHANGE_SAVES_COUNTER";
export const CHANGE_REPOSTS_COUNTER = "CHANGE_REPOSTS_COUNTER";
